export const interviewQuestions = {
  Technical: {
    Fresher: [
      "What is the difference between state and props in React?",
      "What are React Hooks?",
      "What is the Virtual DOM in React?",
      "What is the purpose of useEffect in React?",
      "What is JSX in React?",
      "What is the difference between useState and useReducer?",
      "What is React Context API?",
      "What is the purpose of keys in React lists?",
      "What is the difference between React and JavaScript?",
      "What is a component in React?",
      "What is the difference between functional and class components?",
      "What is conditional rendering in React?",
      "What is the purpose of the useState Hook?",
      "What is the purpose of useEffect Hook?",
      "What is a JavaScript closure?",
      "What is the difference between let, const, and var?",
      "What is the difference between == and === in JavaScript?",
      "What is an array in JavaScript?",
      "What is an object in JavaScript?",
      "What is the DOM?"
    ],

    "1-2 years": [
      "Explain the Virtual DOM and how React uses it.",
      "Explain the difference between controlled and uncontrolled components.",
      "How does useEffect work in React?",
      "What is prop drilling and how can you avoid it?",
      "Explain React Context API with an example.",
      "What is React.memo and when would you use it?",
      "What is useCallback and why is it useful?",
      "What is useMemo and when should you use it?",
      "What is the difference between state and derived state?",
      "How does React reconciliation work?",
      "What are custom Hooks?",
      "How do you handle forms in React?",
      "How do you optimize a React application?",
      "What is lazy loading in React?",
      "What is code splitting?",
      "Explain promises in JavaScript.",
      "Explain async and await.",
      "What is event delegation?",
      "What is the difference between synchronous and asynchronous JavaScript?",
      "What is the JavaScript event loop?"
    ],

    "2-5 years": [
      "Explain React reconciliation in detail.",
      "How would you optimize the performance of a large React application?",
      "Explain React rendering and re-rendering.",
      "How would you manage complex state in a React application?",
      "Compare Context API with a state management library.",
      "How would you design reusable React components?",
      "How would you handle authentication in a React application?",
      "How would you protect routes in React?",
      "Explain code splitting and dynamic imports.",
      "How would you improve the performance of a slow React page?",
      "How would you structure a large React project?",
      "Explain debouncing and throttling.",
      "Explain closures with a practical example.",
      "How does JavaScript garbage collection work?",
      "Explain the prototype chain in JavaScript.",
      "What are higher-order functions?",
      "How does the JavaScript event loop work?",
      "Explain REST APIs.",
      "What is the difference between REST and GraphQL?",
      "How would you design a scalable frontend application?"
    ],

    "5+ years": [
      "How would you architect a large-scale React application?",
      "How would you design a scalable frontend architecture?",
      "How would you optimize React performance for millions of users?",
      "How would you approach frontend system design?",
      "How would you design a reusable component library?",
      "How would you handle state management in a large application?",
      "How would you design a secure authentication system?",
      "How would you handle authorization in a frontend application?",
      "How would you improve the performance of a large React application?",
      "How would you approach micro-frontends?",
      "What are the advantages and disadvantages of micro-frontends?",
      "How would you design frontend error handling?",
      "How would you monitor frontend application performance?",
      "How would you design a highly scalable API integration layer?",
      "How would you handle caching in a frontend application?",
      "How would you approach accessibility in a large application?",
      "How would you design a frontend testing strategy?",
      "How would you handle real-time data in a React application?",
      "How would you design an offline-capable web application?",
      "How would you review the architecture of an existing React application?"
    ]
  },

  HR: {
    Fresher: [
      "Tell me about yourself.",
      "Why should we hire you?",
      "What are your strengths?",
      "What is your biggest weakness?",
      "Why do you want to join our company?",
      "Where do you see yourself in five years?",
      "Why did you choose your field of study?",
      "Tell me about a project you worked on.",
      "What challenges did you face during your project?",
      "How do you handle pressure?",
      "How do you manage your time?",
      "Are you comfortable working in a team?",
      "Tell me about a time you solved a problem.",
      "How do you handle criticism?",
      "What motivates you?",
      "What are your career goals?",
      "Why should we select you over other candidates?",
      "Are you willing to learn new technologies?",
      "What are your salary expectations?",
      "Do you have any questions for us?"
    ],

    "1-2 years": [
      "Tell me about your professional experience.",
      "Why are you looking for a new opportunity?",
      "What is your biggest professional achievement?",
      "Tell me about a difficult situation at work.",
      "How did you handle a conflict with a teammate?",
      "How do you prioritize your tasks?",
      "How do you handle tight deadlines?",
      "Tell me about a mistake you made and what you learned.",
      "How do you handle negative feedback?",
      "What motivates you at work?",
      "What kind of work environment do you prefer?",
      "How do you keep your skills updated?",
      "Tell me about a time you showed leadership.",
      "How do you handle multiple responsibilities?",
      "Why do you want to join our organization?",
      "Where do you see yourself in the next five years?",
      "What are your career goals?",
      "What makes you a good team member?",
      "What are your salary expectations?",
      "Do you have any questions for us?"
    ]
  }
};